# This flow is designed to be used to update the production and beta tracks on the Play store. It does this by promoting the beta track build to production, triggered by the creation of a release tag.
# As per the beta build, this does not actually do a build / upload, it simply promotes whatever's in beta to production. Best to create the
name: Android Release

on:
  push:
    branches:
      - "debugging-gh-actions-is-very-painful"

jobs:
  release:
    name: Create GH release and promote Play store beta to release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch APK from CircleCI
        run: PARPFACE=parpter .github/workflows/fetch-apks.sh
        env:
          CIRCLE_CI_TOKEN: "${{ secrets.CIRCLE_CI_TOKEN }}"
          HEAD_SHA: "${{ env.GITHUB_SHA }}"
